# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Capoeira Senzala Canberra
email: brendan.gordon@gmail.com
description: > #
  Capoeira Senzala Canberra Australia, lead by Mestre Rodriguinho.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://capoirasenzala.com.au" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:

# Build settings
markdown: kramdown
